/home/hubert/projects/driving_platform/lib/Cube/Core/Inc
/home/hubert/projects/driving_platform/lib/Cube/Core/Inc/FreeRTOSConfig.h
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/Core/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/Core_A/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/inc/arr_desc
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/inc
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/inc/opt_arg
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/inc/util
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/basic_math_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/complex_math_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/controller_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/fast_math_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/filtering_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/intrinsics_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/matrix_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/statistics_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/support_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/templates
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/inc/transform_tests
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/inc
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/DSP/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/Device/ST/STM32F4xx/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Compiler
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/_ARMCM0
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/_ARMCM3
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/_ARMCM4_FP
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/_ARMCM7_SP
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Compiler
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/_ARMCM0
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/_ARMCM3
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/_ARMCM4_FP
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/_ARMCM7_SP
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/_ARMCM0
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/_ARMCM3
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/_ARMCM4_FP
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/_ARMCM7_SP
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/RTOS/Template
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/RTOS2/Include
/home/hubert/projects/driving_platform/lib/Cube/Drivers/CMSIS/RTOS2/Template
/home/hubert/projects/driving_platform/lib/Cube/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
/home/hubert/projects/driving_platform/lib/Cube/Drivers/STM32F4xx_HAL_Driver/Inc
/home/hubert/projects/driving_platform/lib/Cube/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
/home/hubert/projects/driving_platform/lib/Cube/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
/home/hubert/projects/driving_platform/lib/Cube/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
/home/hubert/projects/driving_platform/lib/Cube/Middlewares/Third_Party/FreeRTOS/Source/include
/home/hubert/projects/driving_platform/lib/Cube/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
/home/hubert/projects/driving_platform/lib/Cube/USB_DEVICE/App
/home/hubert/projects/driving_platform/lib/Cube/USB_DEVICE/Target 